all:
	@printf "OUTPUTS FOR TEST FILES\n"
	@printf "—————————————————————————————————\n"
	@gcc -o assignment2 assignment2.c
	@printf "inSample1.txt:\n"
	@./assignment2 inSample1.txt
	@printf "—————————————————————————————————\n"
	@printf "inSample2.txt:\n"
	@./assignment2 inSample2.txt
	@printf "—————————————————————————————————\n"
	@printf "inLarge1.txt:\n"
	@./assignment2 inLarge1.txt
	@printf "—————————————————————————————————\n"
	@printf "inLarge2.txt:\n"
	@./assignment2 inLarge2.txt
	@printf "—————————————————————————————————\n"