all:
	@gcc -o test test.c
	@echo "Test 1"
	@./test inSample1.txt
	@./test inSample2.txt
	@./test inLarge1.txt
	@./test inLarge2.txt
	@gcc -o test2 test2.c
	@echo ""
	@echo "Test 2"
	@./test2 inSample1.txt
	@./test2 inSample2.txt
	@./test2 inLarge1.txt
	@./test2 inLarge2.txt
